#!/bin/bash
# Automatically Restart Script

while :
do
    echo "hubserver startup ..."
    ulimit -c unlimited
    ulimit -n 60000

    $PWD/hubserver
	
    $pid = $(ps -ef | grep "$PWD/hubserver" | grep -v "grep")
    wait $pid
    # kill -9 $pidof $PWD/mapserver
    echo `date` ", hubserver crashed and restarted." >> crash.log
done
